import { useState, useEffect } from 'react'
import axios from "axios"
import swal from "sweetalert2"
import base_url from "../api/bootapi"
import invcss from '../css/invoice.css';
import logo from "../images/logo.jpeg";
import { Link } from 'react-router-dom';

export default function Invoice(udata) {
  useEffect(() => {
    alert(udata.city);
    viewAllPricing()
  }, [])

  const [dbPriceData, setDBPricedata] = useState([])
  
  const insertRequest = async (data) => {
    axios.post(`${base_url}/booking`, data).then(
      (response) => {
        swal
          .fire({
            icon: 'Success',
            title: 'Congratulations',
            text:
              'Thanks for choosing us.We will contact you soon via email or phone number to complete your desires.',
          })
          .then(function () {
            window.location = '/payment'
          })
      },
      (error) => {
        swal.fire({
          icon: 'error',
          title: 'Oh no!',
          text: 'Server is down',
        })
      },
    )
  }

  const viewAllPricing = (udata) => {
    axios.get(`${base_url}/pricing`).then(
      (response) => {
        if (response.data.length == 0) {
          swal.fire({
            title: 'Pricing Table',
            text: 'There are no records of price',
            icon: 'error',
            button: 'Ok',
          })
        }
        setDBPricedata(response.data)
      },
      (error) => {
        console.log(error)
        swal.fire({
          icon: 'error',
          title: 'Oh no!',
          text: 'Server is down',
        })
      },
    )
  }

  const bookData = {
    city: 'Mumbai',
    event: 'Wedding',
    date: '20-12-2021',
    guest: '10',
    food: 'Lunch,Dinner,BreakFast',
    equipment: 'DJ,Orchestra',
  }

  // Food value and price  
  const foodArr = bookData.food.split(','); //=>['Lunch','dinner']
  let foodPrice = 0;
  foodArr.forEach(el => {
    for (var i = 0; i < dbPriceData.length; i += 1) {
      if (dbPriceData[i].items === el) {
        console.log(dbPriceData[i].items + " its price is = " + dbPriceData[i].price)
        foodPrice = foodPrice + (dbPriceData[i].price * bookData.guest)
        console.log(foodPrice)
      }
    }
  })

  const equiArr = ['DJ', 'Orchestra']
  bookData.equipment.split(','); //=>['DJ','Orchestra']
  let equiPrice = 0;
  equiArr.forEach(el => {
    for (var i = 0; i < dbPriceData.length; i += 1) {
      if (dbPriceData[i].items === el) {
        equiPrice = equiPrice + dbPriceData[i].price
      }
    }
  })

  //Event 
  var eventPrice;
  for (var i = 0; i < dbPriceData.length; i += 1) {
    if (dbPriceData[i].items === bookData.event) {
      eventPrice = dbPriceData[i].price
    }
  }
  const handleCancle = () => {
    alert(" Price = " + eventPrice)
  }
  const handleBooking = () => {
    alert(JSON.stringify())
  }
  const total = eventPrice + equiPrice + foodPrice;

  return (
    <>
      <div>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous" />
        <link rel="stylesheet" href={invcss} />
        <title>WelcomeHome</title>
        <div className="container ">
          <div className="container">
            <div className="row">
              <div className="col-md-6 col-md-offset-3 body-main">
                <div className="col-md-12">
                  <div className="row">
                    <div className="col-md-4"> <img className="img" alt="Invoice Template" src={logo} /> </div>
                    <div className="col-md-8 text-right">
                      <h4 className="text-primary"><i>Wonder Events</i></h4>
                      <p>425/32,T.M.V Colony,Pune - 411037</p>
                      <p>+91-9822296812</p>
                      <p>wonderevents@gmail.com</p>
                    </div>
                  </div> <br />
                  <div className="row">
                    <div className="col-md-12 text-center">
                      <h2>INVOICE</h2>
                      <h5>Autogenerated</h5>
                    </div>
                  </div> <br />
                  <div>
                    <table className="table">
                      <thead>
                        <tr>
                          <th>
                            <h5>Sr.No.</h5>
                          </th>
                          <th>
                            <h5>Description</h5>
                          </th>
                          <th>
                            <h5>Amount</h5>
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td className="col-md-1">1</td>
                          <td className="col-md-8">{bookData.event} </td>
                          <td className="col-md-3"><i className="fas fa-rupee-sign" area-hidden="true" />
                            {eventPrice}
                          </td>
                        </tr>
                        <tr>
                          <td className="col-md-1">1</td>
                          <td className="col-md-8">{bookData.food} </td>
                          <td className="col-md-3"><i className="fas fa-rupee-sign" area-hidden="true" />
                            {foodPrice}
                          </td>
                        </tr>
                        <tr>
                          <td className="col-md-1">1</td>
                          <td className="col-md-8">{bookData.equipment} </td>
                          <td className="col-md-3"><i className="fas fa-rupee-sign" area-hidden="true" />
                            {equiPrice}
                          </td>
                        </tr>
                        
                        <tr>
                          <td className="text-right">
                            <p>  </p>
                            <p>  </p>
                            <p> </p>
                            <p>  </p>
                          </td>
                          <td className="text-right">
                            <p> <strong>Shipment and Taxes:</strong> </p>
                            <p> <strong>Total Amount: </strong> </p>
                            <p> <strong>Discount: </strong> </p>
                            <p> <strong>Payable Amount: </strong> </p>
                          </td>
                          <td>
                            <p> <strong><i className="fas fa-rupee-sign" area-hidden="true" /> 500
                            </strong> </p>
                            <p> <strong><i className="fas fa-rupee-sign" area-hidden="true" />
                              82,900</strong> </p>
                            <p> <strong><i className="fas fa-rupee-sign" area-hidden="true" /> 3,000
                            </strong> </p>
                            <p> <strong><i className="fas fa-rupee-sign" area-hidden="true" />
                              79,900</strong> </p>
                          </td>
                        </tr>
                        <tr>
                          <td className="text-right">
                            <h4></h4>
                          </td>
                          <td className="text-right">
                            <h4><strong>Total:</strong></h4>
                          </td>
                          <td className="text-left text-primary">
                            <h4><strong><i className="fas fa-rupee-sign" area-hidden="true" /> {total}
                            </strong></h4>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <div>
                    <div className="col-md-12">
                      <p><b>Date :</b> Autogenerated</p> <br />
                      <p><b>Signature</b></p>
                    </div>
                    <Link to='/home'> <button className='btn-lg btn-dark'>Home</button> </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
       <div id="invoice">
        <span>Items</span> : <span>ItemsPrice</span> <br />
        <span>{bookData.event} </span>  :  <span> {eventPrice} </span> <br />
        <span>Number of Guests </span>  : <span>{bookData.guest} </span> <br />
        <span>{bookData.food} </span>  : <span>{foodPrice} </span> <br />
        <span>{bookData.equipment} </span>  : <span>{equiPrice} </span> <br/>

        <span>Total</span> : <span>{total} </span>

      </div>
      <div>
        <input
          type="button"
          value="Pay now & Confirm Booking"
          className="btn btn-primary btn-lg ps-2 pe-3 p-1 m-3"
          onClick={handleBooking}
        />
        <input
          type="button"
          value="Cancle"
          className="btn btn-primary btn-lg ps-2 pe-3 p-1 m-3"
          onClick={handleCancle}
        />
      </div> 
    </>
  )
}
